# Generated by Django 3.0.5 on 2020-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.CharField(default='https://lichi-a.akamaihd.net/product/38348/thumbs/ff2c89c5a1f0a18fae140da8e2f31c8b_768_1024.jpg?v=0_3842912', max_length=500),
        ),
    ]
